ssh no pass validation check

diff --git a/src/sshnp b/src/sshnp
--- a/src/sshnp
+++ b/src/sshnp
@@ -1,10 +1,27 @@
-#USAGE ssh_nopass_init <uname>@<server_ip>:<server_port>
-cmd_name="sshnp"
+#!/bin/bash
+
+# Backup website ( code and database )
+#
+#		Author	: Viki (a) Vignesh Natarajan 
+#		Contact	: vikilabs.org
+#		Licence : MIT
+
+ARG0="$0"
+ARG1="$1"
+ARG2="$2"
+ARG3="$3"
+ARG4="$4"
+CMD="$ARG0"
+
 SERVER_DETAILS=""
 UNAME=""
 SERVER_IP=""
 SERVER_PORT=""
-SSH_KEY_PREFIX=""
+SSH_KEY_PATH="$HOME/.ssh"
+
+SSH_KEY_PUBLIC=""
+SSH_KEY_PRIVATE=""
+
 DEBUG_LEVEL="error"  # "quite", "debug", "error"
 
 replace_dots_with_dash () {
@@ -131,8 +148,14 @@ validate_server_details_at_arg1() {
 
 
 parse_server_details() {
-    UNAME=`echo $1  | awk -F@ '{print $1}'`
-    TEMP_STR=`echo $1  | awk -F@ '{print $2}'`
+    [ -z $SERVER_DETAILS ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+    
+    validate_server_details $SERVER_DETAILS
+    
+    [ -z $SERVER_DETAILS ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+
+    UNAME=`echo $SERVER_DETAILS  | awk -F@ '{print $1}'`
+    TEMP_STR=`echo $SERVER_DETAILS  | awk -F@ '{print $2}'`
     SERVER_IP=`echo $TEMP_STR  | awk -F: '{print $1}'`
     SERVER_PORT=`echo $TEMP_STR  | awk -F: '{print $2}'`
 
@@ -140,38 +163,39 @@ parse_server_details() {
         SERVER_PORT="22"
     fi
 
-    SSH_KEY_PREFIX="$(replace_dots_with_dash $SERVER_IP)"
-    SSH_KEY_PREFIX=$UNAME"_"$SSH_KEY_PREFIX"_"$SERVER_PORT
+    [ -z $UNAME ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+    [ -z $SERVER_IP ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+    [ -z $SERVER_PORT ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+    [ -z $SERVER_DETAILS ] && { echo "  error: ( ${LINENO} )"; exit 1; }
 }
 
 print_connection_details() {
+    echo "  Remote Host Details :"
     echo
-    echo "Remote Host Details :"
-    echo
-    echo "  User Name         : " $UNAME
-    echo "  Server IP         : " $SERVER_IP
-    echo "  Server SSH Port   : " $SERVER_PORT
-    echo "  SSH Key Prefix    : " $SSH_KEY_PREFIX
-    echo
+    echo "    User Name         : " $UNAME
+    echo "    Server IP         : " $SERVER_IP
+    echo "    Server SSH Port   : " $SERVER_PORT
+    echo "    SSH Key Public    : " $SSH_KEY_PUBLIC
+    echo "    SSH Key Private   : " $SSH_KEY_PRIVATE
 }
 
 
 #prerequisite check
-verify_essential_packages() {
+prerequisite_check(){
     ExecAndExitOnError $DEBUG_LEVEL "which ssh-keygen &> /dev/null"  "Install package ( ssh-keygen ) before using this utility"
     ExecAndExitOnError $DEBUG_LEVEL "which ssh &> /dev/null"         "Install package ( ssh ) before using this utility"
     ExecAndExitOnError $DEBUG_LEVEL "which scp &> /dev/null"         "Install package ( scp ) before using this utility"
 }
 
 local_verify_keys(){
-	F_PUBLIC_KEY="$HOME/.ssh/$SSH_KEY_PREFIX.pub"	
+	F_PUBLIC_KEY="$SSH_KEY_PATH/$SSH_KEY_PUBLIC"	
 	if [ ! -f "$F_PUBLIC_KEY" ]; then
 		echo "[ notice ] ssh public key missing"
         	enable_ssh_nopass $SERVER_DETAILS
 		return 0
 	fi
 
-	F_PRIVATE_KEY="$HOME/.ssh/$SSH_KEY_PREFIX"
+	F_PRIVATE_KEY="$SSH_KEY_PATH/$SSH_KEY_PRIVATE"
 	if [ ! -f "$F_PRIVATE_KEY" ]; then 
 		echo "[ notice ] ssh private key missing"
         	enable_ssh_nopass $SERVER_DETAILS
@@ -180,77 +204,69 @@ local_verify_keys(){
 }
 
 local_delete_old_keys() {
+    echo "  [ status ] deleting old key ( $SSH_KEY_PATH/$SSH_KEY_PUBLIC )"
+    echo "  [ status ] deleting old key ( $SSH_KEY_PATH/$SSH_KEY_PRIVATE )"
     #Need to just check if file exist or create seperate keys for new servers
-    ExecCmd "quite" "rm -rf $HOME/.ssh/$SSH_KEY_PREFIX"
-    ExecCmd "quite" "rm -rf $HOME/.ssh/$SSH_KEY_PREFIX.pub"
+    ExecCmd "quite" "rm -rf $SSH_KEY_PATH/$SSH_KEY_PUBLIC"
+    ExecCmd "quite" "rm -rf $SSH_KEY_PATH/$SSH_KEY_PRIVATE"
 }
 
 generate_rsa_keys() {
-    ExecAndExitOnError "error" "ssh-keygen -q -N '' -t rsa -b 1024 -f $HOME/.ssh/$SSH_KEY_PREFIX &> /dev/null"
+    echo "  [ status ] generating rsa key ( $SSH_KEY_PATH/$SSH_KEY_PRIVATE )"
+
+    ExecAndExitOnError "error" "ssh-keygen -q -N '' -t rsa -b 1024 -f $SSH_KEY_PATH/$SSH_KEY_PRIVATE &> /dev/null"
 }
 
-
-remote_add_public_key_to_authorized_keys() {
-    #In remote server copy /tmp/$SSH_KEY_PREFIX.pub to .ssh/authorized_keys and .ssh/known_hosts
-    ssh $UNAME@$SERVER_IP -p $SERVER_PORT -t "mkdir -p ~/.ssh; cat ~/.ssh/$SSH_KEY_PREFIX.pub >> ~/.ssh/authorized_keys; cat ~/.ssh/$SSH_KEY_PREFIX.pub >> ~/.ssh/known_hosts;"
-}
 
 remote_upload_public_key(){
-    ExecAndExitOnError "error" "scp -r -P $SERVER_PORT $HOME/.ssh/$SSH_KEY_PREFIX.pub $UNAME@$SERVER_IP:~/.ssh/" "ssh public key upload"
+    echo "  [ status ] uploading key to remote host ( $SSH_KEY_PATH/$SSH_KEY_PUBLIC )"
+    echo
+    echo
+    ExecAndExitOnError "error" "ssh-copy-id -p $SERVER_PORT -i $SSH_KEY_PATH/$SSH_KEY_PUBLIC $UNAME@$SERVER_IP  &> /dev/null" "ssh public key upload"
 }
 
 remote_delete_public_key(){
-    ssh $UNAME@$SERVER_IP -p $SERVER_PORT -t "rm ~/.ssh/$SSH_KEY_PREFIX.pub 2> /dev/null;"
+    REMOVE_COMMAND="rm ~/.ssh/$SSH_KEY_PUBLIC 2> /dev/null;"
+    ssh $UNAME@$SERVER_IP -p $SERVER_PORT -t "$REMOVE_COMMAND"
 }
 
 usage() {
     echo 
-    echo "<------------------  Usage Instruction --------------------->" 
+    echo "  <------------------  Usage Instruction --------------------->" 
     echo
-    echo "List of command options for password less ssh utility"
+    echo "  Connect / Enable passwordless ssh"
     echo
-    echo "  "$cmd_name " <username>@<domain/ip_address>""                -> [ connect to server without password ]"
-    echo "  "$cmd_name " <username>@<domain/ip_address>:<port>""         -> [ connect to server without password ]"
-    echo "  "$cmd_name " disable <username>@<domain/ip_address>""        -> [ disable password less ssh]"
-    echo "  "$cmd_name " disable <username>@<domain/ip_address>:<port>"" -> [ disable password less ssh]"
+    echo "    "$CMD " <username>@<domain/ip_address>""                -> [ connect to server without password ]"
+    echo "    "$CMD " <username>@<domain/ip_address>:<port>""         -> [ connect to server without password ]"
+    echo
+    echo "  Disable passwordless ssh"
+    echo
+    echo "    "$CMD " -d <username>@<domain/ip_address>""        -> [ disable password less ssh]"
+    echo "    "$CMD " -d <username>@<domain/ip_address>:<port>"" -> [ disable password less ssh]"
     echo
     echo
 }
 
 enable_ssh_nopass(){
-    echo "[ status ] initializing passwordless ssh"
-    echo
-    SERVER_DETAILS=$1
-    parse_server_details $SERVER_DETAILS
     local_delete_old_keys
     generate_rsa_keys 
     remote_upload_public_key
-    remote_add_public_key_to_authorized_keys
-    echo
     #echo "[ status ] passwordless ssh initialized"
 }
 
 disable_ssh_nopass(){
-    SERVER_DETAILS=$1
-    validate_server_details $SERVER_DETAILS
-    parse_server_details $SERVER_DETAILS
     #print_connection_details
-    verify_essential_packages
+    #remote_delete_public_key
     local_delete_old_keys
-    remote_delete_public_key
-    echo
-    echo "[ status ] passwordless ssh is disabled"
+    echo "  [ status ] passwordless ssh is disabled"
 }
 
 ssh_nopass_connect() {
-    SERVER_DETAILS=$1
     validate_server_details_at_arg1 $SERVER_DETAILS
-    parse_server_details $SERVER_DETAILS
     #print_connection_details
-    verify_essential_packages
     #echo "[ status ] connecting to remote host"
     
-    ssh $UNAME@$SERVER_IP -p $SERVER_PORT -i $HOME/.ssh/$SSH_KEY_PREFIX -o PasswordAuthentication=no 2> /dev/null 
+    ssh $UNAME@$SERVER_IP -p $SERVER_PORT -i $SSH_KEY_PATH/$SSH_KEY_PRIVATE -o PasswordAuthentication=no 2> /dev/null 
     
     if [ $? -ne 0 ]; then
 
@@ -258,8 +274,11 @@ ssh_nopass_connect() {
         echo
 
 	enable_ssh_nopass $SERVER_DETAILS
-    
-    	ssh $UNAME@$SERVER_IP -p $SERVER_PORT -i $HOME/.ssh/$SSH_KEY_PREFIX -o PasswordAuthentication=no 2> /dev/null
+   
+	echo
+	echo " connecting to server : $SERVER_IP"
+	echo 
+    	ssh $UNAME@$SERVER_IP -p $SERVER_PORT -i $SSH_KEY_PATH/$SSH_KEY_PRIVATE -o PasswordAuthentication=no 2> /dev/null
 
     	if [ $? -ne 0 ]; then
     		echo "[ error ] sshnp is not initialized | private/public key is malformed"
@@ -269,29 +288,54 @@ ssh_nopass_connect() {
  
 }
 
-ssh_nopass_main() {
-    if [ "$1" = "disable" ]; then
-        SERVER_DETAILS=$2
-        echo "[ status ] disabling password less ssh"
-        disable_ssh_nopass $SERVER_DETAILS
+get_server_details() {
+    if [ "$ARG1" = "-d" ]; then
+        SERVER_DETAILS="$ARG2"
     else
-        SERVER_DETAILS=$1
-        ssh_nopass_connect $SERVER_DETAILS
+        SERVER_DETAILS="$ARG1"
     fi
 }
 
-if [ $# -lt 1 ]; then
-    echo
-    echo "[ error ] usage "
-    usage
-    exit 1
-fi
+generate_key_labels(){
 
-echo
-ssh_nopass_main $1 $2
-echo
+    [ -z $SERVER_IP ] && { echo "  error:  server ip missing ( ${LINENO} )"; exit 1; }
 
-exit 1
+    IP_LABEL="$(replace_dots_with_dash $SERVER_IP)"
+
+    [ -z $IP_LABEL ] && { echo "  error: IP_LABEL generation ( ${LINENO} )"; exit 1; }
+
+    SSH_KEY_LABEL=$UNAME"_"$IP_LABEL"_"$SERVER_PORT
+      
+    SSH_KEY_PUBLIC="$SSH_KEY_LABEL.pub"
+    SSH_KEY_PRIVATE="$SSH_KEY_LABEL" 
+
+    [ -z $SSH_KEY_PUBLIC ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+    [ -z $SSH_KEY_PRIVATE ] && { echo "  error: ( ${LINENO} )"; exit 1; }
+}
+
+main_logic() {
+    if [ "$ARG1" = "-d" ]; then
+        echo "  [ status ] disabling password less ssh"
+        disable_ssh_nopass
+    else
+        ssh_nopass_connect
+    fi
+}
+
+usage_check(){
+    if [ -z $ARG1 ]; then
+	echo
+        echo "  [ error ] usage "
+	usage
+	exit 1
+    fi
+}
 
 
+usage_check
+prerequisite_check
+get_server_details
+parse_server_details
+generate_key_labels
+main_logic
 
